// Generated by CoffeeScript 1.4.0
(function() {
  var Bacon, Gaze, child_process, files, fs, glob, mkdirp, path;

  Bacon = require('baconjs').Bacon;

  Gaze = require('gaze').Gaze;

  fs = require('fs');

  child_process = require('child_process');

  path = require('path');

  mkdirp = require('mkdirp');

  glob = require('glob');

  exports.watch = function(pattern) {
    var gazer, gazerStream;
    gazer = new Gaze(pattern);
    return gazerStream = Bacon.fromEventTarget(gazer, 'all', function(event, filename) {
      return [
        {
          name: filename,
          content: fs.readFileSync(filename, 'utf8')
        }
      ];
    }).toProperty(files(pattern));
  };

  exports.files = files = function(pattern) {
    return glob.sync(pattern).map(function(filename) {
      return {
        name: filename,
        content: fs.readFileSync(filename, 'utf8')
      };
    });
  };

  exports.write = function(files) {
    return files.map(function(file) {
      mkdirp.sync(path.dirname(file.name));
      return fs.writeFileSync(file.name, file.content, 'utf8');
    });
  };

}).call(this);
